-- ============================================================================
-- Read-only verification for database-upgrade-04a1acb-to-current.sql
-- Baseline: 04a1acb | Target: current shared/schema.ts
-- Every query in this file is read-only. Empty result sets indicate success for
-- the corresponding missing-object query.
-- ============================================================================

-- 1. Required tables missing from public schema (expected: zero rows).
WITH expected(table_name) AS (VALUES
  ('attendance_audit_log'),
  ('attendance_exceptions'),
  ('attendance_location_checkpoints'),
  ('attendance_sessions'),
  ('bc_order_line_items'),
  ('crm_audit_log'),
  ('crm_customer_notes'),
  ('customer_orders_mirror'),
  ('customer_sales_rep'),
  ('customer_signup_attempts'),
  ('customer_signups'),
  ('customers_mirror'),
  ('email_templates'),
  ('inventory_audit_tasks'),
  ('inventory_push_logs'),
  ('marketing_audience_members'),
  ('marketing_audiences'),
  ('marketing_automation_executions'),
  ('marketing_automation_steps'),
  ('marketing_automations'),
  ('marketing_campaign_activity'),
  ('marketing_campaign_events'),
  ('marketing_campaign_recipients'),
  ('marketing_campaigns'),
  ('marketing_contacts'),
  ('marketing_customer_preferences'),
  ('marketing_suppressions'),
  ('notifications'),
  ('orders'),
  ('permissions'),
  ('pos_price_override_audit'),
  ('pos_store_credit_usage'),
  ('price_history_cache'),
  ('product_link_logs'),
  ('products'),
  ('promo_free_sku_tracker'),
  ('report_export_logs'),
  ('role_permissions'),
  ('roles'),
  ('settings'),
  ('shipstation_export_history'),
  ('store_credit_ledger'),
  ('user_permissions'),
  ('users')
)
SELECT e.table_name AS missing_table
FROM expected e
LEFT JOIN information_schema.tables t
  ON t.table_schema = 'public' AND t.table_name = e.table_name
WHERE t.table_name IS NULL
ORDER BY e.table_name;

-- 2. Required columns missing from public schema (expected: zero rows).
WITH expected(table_name, column_name) AS (VALUES
  ('attendance_audit_log', 'id'),
  ('attendance_audit_log', 'attendance_id'),
  ('attendance_audit_log', 'actor_user_id'),
  ('attendance_audit_log', 'action'),
  ('attendance_audit_log', 'changed_field'),
  ('attendance_audit_log', 'old_value'),
  ('attendance_audit_log', 'new_value'),
  ('attendance_audit_log', 'reason'),
  ('attendance_audit_log', 'created_at'),
  ('attendance_exceptions', 'id'),
  ('attendance_exceptions', 'attendance_id'),
  ('attendance_exceptions', 'user_id'),
  ('attendance_exceptions', 'exception_type'),
  ('attendance_exceptions', 'details'),
  ('attendance_exceptions', 'status'),
  ('attendance_exceptions', 'detected_at'),
  ('attendance_exceptions', 'reviewed_by'),
  ('attendance_exceptions', 'reviewed_at'),
  ('attendance_exceptions', 'review_notes'),
  ('attendance_location_checkpoints', 'id'),
  ('attendance_location_checkpoints', 'attendance_id'),
  ('attendance_location_checkpoints', 'captured_at'),
  ('attendance_location_checkpoints', 'latitude'),
  ('attendance_location_checkpoints', 'longitude'),
  ('attendance_location_checkpoints', 'accuracy'),
  ('attendance_location_checkpoints', 'checkpoint_type'),
  ('attendance_location_checkpoints', 'capture_status'),
  ('attendance_location_checkpoints', 'detail'),
  ('attendance_location_checkpoints', 'created_at'),
  ('attendance_sessions', 'id'),
  ('attendance_sessions', 'user_id'),
  ('attendance_sessions', 'work_date'),
  ('attendance_sessions', 'time_in'),
  ('attendance_sessions', 'time_out'),
  ('attendance_sessions', 'start_method'),
  ('attendance_sessions', 'status'),
  ('attendance_sessions', 'total_seconds'),
  ('attendance_sessions', 'time_in_latitude'),
  ('attendance_sessions', 'time_in_longitude'),
  ('attendance_sessions', 'time_in_accuracy'),
  ('attendance_sessions', 'time_in_verification'),
  ('attendance_sessions', 'time_out_latitude'),
  ('attendance_sessions', 'time_out_longitude'),
  ('attendance_sessions', 'time_out_accuracy'),
  ('attendance_sessions', 'time_out_verification'),
  ('attendance_sessions', 'driving_verified'),
  ('attendance_sessions', 'driving_verified_at'),
  ('attendance_sessions', 'review_status'),
  ('attendance_sessions', 'approved_by'),
  ('attendance_sessions', 'approved_at'),
  ('attendance_sessions', 'locked_at'),
  ('attendance_sessions', 'created_at'),
  ('attendance_sessions', 'updated_at'),
  ('bc_order_line_items', 'id'),
  ('bc_order_line_items', 'bigcommerce_order_id'),
  ('bc_order_line_items', 'bigcommerce_product_id'),
  ('bc_order_line_items', 'variant_id'),
  ('bc_order_line_items', 'product_name'),
  ('bc_order_line_items', 'sku'),
  ('bc_order_line_items', 'variant_label'),
  ('bc_order_line_items', 'quantity'),
  ('bc_order_line_items', 'base_price'),
  ('bc_order_line_items', 'order_date'),
  ('bc_order_line_items', 'customer_name'),
  ('bc_order_line_items', 'customer_email'),
  ('bc_order_line_items', 'bigcommerce_customer_id'),
  ('bc_order_line_items', 'created_at'),
  ('crm_audit_log', 'id'),
  ('crm_audit_log', 'user_id'),
  ('crm_audit_log', 'action'),
  ('crm_audit_log', 'customer_id'),
  ('crm_audit_log', 'detail'),
  ('crm_audit_log', 'created_at'),
  ('crm_customer_notes', 'id'),
  ('crm_customer_notes', 'customer_id'),
  ('crm_customer_notes', 'note_type'),
  ('crm_customer_notes', 'note'),
  ('crm_customer_notes', 'order_id'),
  ('crm_customer_notes', 'created_by'),
  ('crm_customer_notes', 'activity_type'),
  ('crm_customer_notes', 'title'),
  ('crm_customer_notes', 'assigned_to_user_id'),
  ('crm_customer_notes', 'priority'),
  ('crm_customer_notes', 'due_date'),
  ('crm_customer_notes', 'completed_at'),
  ('crm_customer_notes', 'reminder_at'),
  ('crm_customer_notes', 'todo_status'),
  ('crm_customer_notes', 'created_at'),
  ('crm_customer_notes', 'updated_at'),
  ('customer_orders_mirror', 'id'),
  ('customer_orders_mirror', 'bigcommerce_order_id'),
  ('customer_orders_mirror', 'bigcommerce_customer_id'),
  ('customer_orders_mirror', 'order_number'),
  ('customer_orders_mirror', 'order_date'),
  ('customer_orders_mirror', 'order_total'),
  ('customer_orders_mirror', 'status'),
  ('customer_orders_mirror', 'payment_status'),
  ('customer_orders_mirror', 'customer_name'),
  ('customer_orders_mirror', 'customer_email'),
  ('customer_orders_mirror', 'staff_notes'),
  ('customer_orders_mirror', 'customer_order_notes'),
  ('customer_orders_mirror', 'created_at'),
  ('customer_orders_mirror', 'updated_at'),
  ('customer_sales_rep', 'id'),
  ('customer_sales_rep', 'customer_id'),
  ('customer_sales_rep', 'assigned_user_id'),
  ('customer_sales_rep', 'assigned_at'),
  ('customer_sales_rep', 'assigned_by'),
  ('customer_signup_attempts', 'idempotency_key'),
  ('customer_signup_attempts', 'created_by_user_id'),
  ('customer_signup_attempts', 'request_data'),
  ('customer_signup_attempts', 'bigcommerce_customer_id'),
  ('customer_signup_attempts', 'status'),
  ('customer_signup_attempts', 'result'),
  ('customer_signup_attempts', 'created_at'),
  ('customer_signup_attempts', 'updated_at'),
  ('customer_signups', 'id'),
  ('customer_signups', 'bigcommerce_customer_id'),
  ('customer_signups', 'first_name'),
  ('customer_signups', 'last_name'),
  ('customer_signups', 'email'),
  ('customer_signups', 'company'),
  ('customer_signups', 'customer_group_id'),
  ('customer_signups', 'customer_group_name'),
  ('customer_signups', 'attribution'),
  ('customer_signups', 'shipping_address'),
  ('customer_signups', 'signed_up_by_user_id'),
  ('customer_signups', 'signed_up_by_name'),
  ('customer_signups', 'primary_rep_id'),
  ('customer_signups', 'created_at'),
  ('customers_mirror', 'id'),
  ('customers_mirror', 'bigcommerce_customer_id'),
  ('customers_mirror', 'company'),
  ('customers_mirror', 'first_name'),
  ('customers_mirror', 'last_name'),
  ('customers_mirror', 'email'),
  ('customers_mirror', 'phone'),
  ('customers_mirror', 'customer_group_id'),
  ('customers_mirror', 'customer_group_name'),
  ('customers_mirror', 'billing_address'),
  ('customers_mirror', 'shipping_address'),
  ('customers_mirror', 'created_date'),
  ('customers_mirror', 'last_order_date'),
  ('customers_mirror', 'lifetime_orders'),
  ('customers_mirror', 'lifetime_revenue'),
  ('customers_mirror', 'store_credit_balance'),
  ('customers_mirror', 'is_active'),
  ('customers_mirror', 'account_health'),
  ('customers_mirror', 'primary_rep_id'),
  ('customers_mirror', 'secondary_rep_id'),
  ('customers_mirror', 'customer_type'),
  ('customers_mirror', 'address_type'),
  ('customers_mirror', 'account_type'),
  ('customers_mirror', 'inactive_reason'),
  ('customers_mirror', 'inactive_at'),
  ('customers_mirror', 'inactive_notes'),
  ('customers_mirror', 'inactivated_by_user_id'),
  ('customers_mirror', 'created_at'),
  ('customers_mirror', 'updated_at'),
  ('email_templates', 'id'),
  ('email_templates', 'key'),
  ('email_templates', 'name'),
  ('email_templates', 'subject_template'),
  ('email_templates', 'body'),
  ('email_templates', 'template_type'),
  ('email_templates', 'category'),
  ('email_templates', 'is_active'),
  ('email_templates', 'archived_at'),
  ('email_templates', 'updated_at'),
  ('email_templates', 'updated_by'),
  ('inventory_audit_tasks', 'id'),
  ('inventory_audit_tasks', 'sku'),
  ('inventory_audit_tasks', 'product_id'),
  ('inventory_audit_tasks', 'variant_id'),
  ('inventory_audit_tasks', 'product_name'),
  ('inventory_audit_tasks', 'variant_name'),
  ('inventory_audit_tasks', 'status'),
  ('inventory_audit_tasks', 'source'),
  ('inventory_audit_tasks', 'total_push_qty'),
  ('inventory_audit_tasks', 'push_count'),
  ('inventory_audit_tasks', 'last_push_at'),
  ('inventory_audit_tasks', 'system_qty'),
  ('inventory_audit_tasks', 'physical_qty'),
  ('inventory_audit_tasks', 'variance'),
  ('inventory_audit_tasks', 'reason'),
  ('inventory_audit_tasks', 'notes'),
  ('inventory_audit_tasks', 'skuvault_result'),
  ('inventory_audit_tasks', 'skuvault_location'),
  ('inventory_audit_tasks', 'created_at'),
  ('inventory_audit_tasks', 'completed_at'),
  ('inventory_audit_tasks', 'created_by'),
  ('inventory_audit_tasks', 'completed_by'),
  ('inventory_push_logs', 'id'),
  ('inventory_push_logs', 'user_id'),
  ('inventory_push_logs', 'username'),
  ('inventory_push_logs', 'sku'),
  ('inventory_push_logs', 'product_id'),
  ('inventory_push_logs', 'variant_id'),
  ('inventory_push_logs', 'product_name'),
  ('inventory_push_logs', 'variant_name'),
  ('inventory_push_logs', 'previous_inventory'),
  ('inventory_push_logs', 'new_inventory'),
  ('inventory_push_logs', 'quantity_added'),
  ('inventory_push_logs', 'reason'),
  ('inventory_push_logs', 'push_to_bigcommerce'),
  ('inventory_push_logs', 'push_to_skuvault'),
  ('inventory_push_logs', 'skuvault_location'),
  ('inventory_push_logs', 'created_at'),
  ('marketing_audience_members', 'id'),
  ('marketing_audience_members', 'audience_id'),
  ('marketing_audience_members', 'customer_id'),
  ('marketing_audience_members', 'marketing_contact_id'),
  ('marketing_audience_members', 'created_at'),
  ('marketing_audiences', 'id'),
  ('marketing_audiences', 'name'),
  ('marketing_audiences', 'description'),
  ('marketing_audiences', 'audience_type'),
  ('marketing_audiences', 'dynamic_filters'),
  ('marketing_audiences', 'created_by'),
  ('marketing_audiences', 'created_at'),
  ('marketing_audiences', 'updated_at'),
  ('marketing_automation_executions', 'id'),
  ('marketing_automation_executions', 'automation_id'),
  ('marketing_automation_executions', 'customer_id'),
  ('marketing_automation_executions', 'trigger_event'),
  ('marketing_automation_executions', 'dedupe_key'),
  ('marketing_automation_executions', 'status'),
  ('marketing_automation_executions', 'current_step'),
  ('marketing_automation_executions', 'detail'),
  ('marketing_automation_executions', 'error_message'),
  ('marketing_automation_executions', 'started_at'),
  ('marketing_automation_executions', 'completed_at'),
  ('marketing_automation_executions', 'created_at'),
  ('marketing_automation_steps', 'id'),
  ('marketing_automation_steps', 'automation_id'),
  ('marketing_automation_steps', 'step_order'),
  ('marketing_automation_steps', 'action_type'),
  ('marketing_automation_steps', 'action_config'),
  ('marketing_automation_steps', 'created_at'),
  ('marketing_automations', 'id'),
  ('marketing_automations', 'name'),
  ('marketing_automations', 'description'),
  ('marketing_automations', 'trigger_type'),
  ('marketing_automations', 'trigger_config'),
  ('marketing_automations', 'status'),
  ('marketing_automations', 'frequency_days'),
  ('marketing_automations', 'created_by'),
  ('marketing_automations', 'created_at'),
  ('marketing_automations', 'updated_at'),
  ('marketing_campaign_activity', 'id'),
  ('marketing_campaign_activity', 'campaign_id'),
  ('marketing_campaign_activity', 'user_id'),
  ('marketing_campaign_activity', 'action'),
  ('marketing_campaign_activity', 'detail'),
  ('marketing_campaign_activity', 'created_at'),
  ('marketing_campaign_events', 'id'),
  ('marketing_campaign_events', 'campaign_id'),
  ('marketing_campaign_events', 'recipient_id'),
  ('marketing_campaign_events', 'event_type'),
  ('marketing_campaign_events', 'provider_event_id'),
  ('marketing_campaign_events', 'detail'),
  ('marketing_campaign_events', 'occurred_at'),
  ('marketing_campaign_events', 'created_at'),
  ('marketing_campaign_recipients', 'id'),
  ('marketing_campaign_recipients', 'campaign_id'),
  ('marketing_campaign_recipients', 'customer_id'),
  ('marketing_campaign_recipients', 'marketing_contact_id'),
  ('marketing_campaign_recipients', 'email'),
  ('marketing_campaign_recipients', 'status'),
  ('marketing_campaign_recipients', 'is_test'),
  ('marketing_campaign_recipients', 'attempt_count'),
  ('marketing_campaign_recipients', 'last_attempt_at'),
  ('marketing_campaign_recipients', 'sent_at'),
  ('marketing_campaign_recipients', 'failure_reason'),
  ('marketing_campaign_recipients', 'provider_message_id'),
  ('marketing_campaign_recipients', 'unsubscribed_at'),
  ('marketing_campaign_recipients', 'created_at'),
  ('marketing_campaigns', 'id'),
  ('marketing_campaigns', 'name'),
  ('marketing_campaigns', 'internal_description'),
  ('marketing_campaigns', 'campaign_type'),
  ('marketing_campaigns', 'subject_line'),
  ('marketing_campaigns', 'preview_text'),
  ('marketing_campaigns', 'message_content'),
  ('marketing_campaigns', 'sender_email'),
  ('marketing_campaigns', 'audience_type'),
  ('marketing_campaigns', 'audience_id'),
  ('marketing_campaigns', 'audience_config'),
  ('marketing_campaigns', 'template_id'),
  ('marketing_campaigns', 'product_snapshots'),
  ('marketing_campaigns', 'product_display_options'),
  ('marketing_campaigns', 'status'),
  ('marketing_campaigns', 'scheduled_at'),
  ('marketing_campaigns', 'timezone'),
  ('marketing_campaigns', 'queued_at'),
  ('marketing_campaigns', 'started_at'),
  ('marketing_campaigns', 'sent_at'),
  ('marketing_campaigns', 'completed_at'),
  ('marketing_campaigns', 'last_error'),
  ('marketing_campaigns', 'send_attempts'),
  ('marketing_campaigns', 'recipient_count'),
  ('marketing_campaigns', 'sent_count'),
  ('marketing_campaigns', 'failed_count'),
  ('marketing_campaigns', 'suppressed_count'),
  ('marketing_campaigns', 'unsubscribed_count'),
  ('marketing_campaigns', 'delivered_count'),
  ('marketing_campaigns', 'opened_count'),
  ('marketing_campaigns', 'clicked_count'),
  ('marketing_campaigns', 'test_sent_at'),
  ('marketing_campaigns', 'created_by'),
  ('marketing_campaigns', 'created_at'),
  ('marketing_campaigns', 'updated_at'),
  ('marketing_contacts', 'id'),
  ('marketing_contacts', 'email'),
  ('marketing_contacts', 'first_name'),
  ('marketing_contacts', 'last_name'),
  ('marketing_contacts', 'company'),
  ('marketing_contacts', 'phone'),
  ('marketing_contacts', 'contact_type'),
  ('marketing_contacts', 'source'),
  ('marketing_contacts', 'is_active'),
  ('marketing_contacts', 'created_by'),
  ('marketing_contacts', 'created_at'),
  ('marketing_contacts', 'updated_at'),
  ('marketing_customer_preferences', 'id'),
  ('marketing_customer_preferences', 'customer_id'),
  ('marketing_customer_preferences', 'email_subscribed'),
  ('marketing_customer_preferences', 'unsubscribed_at'),
  ('marketing_customer_preferences', 'updated_by'),
  ('marketing_customer_preferences', 'updated_at'),
  ('marketing_suppressions', 'id'),
  ('marketing_suppressions', 'customer_id'),
  ('marketing_suppressions', 'email'),
  ('marketing_suppressions', 'reason'),
  ('marketing_suppressions', 'source'),
  ('marketing_suppressions', 'created_by'),
  ('marketing_suppressions', 'created_at'),
  ('marketing_suppressions', 'revoked_at'),
  ('marketing_suppressions', 'revoked_by'),
  ('marketing_suppressions', 'revoked_at_detail'),
  ('notifications', 'id'),
  ('notifications', 'user_id'),
  ('notifications', 'customer_id'),
  ('notifications', 'message'),
  ('notifications', 'notification_type'),
  ('notifications', 'is_read'),
  ('notifications', 'link_url'),
  ('notifications', 'created_at'),
  ('orders', 'id'),
  ('orders', 'customer_name'),
  ('orders', 'customer_email'),
  ('orders', 'bigcommerce_customer_id'),
  ('orders', 'billing_address'),
  ('orders', 'status'),
  ('orders', 'sync_error'),
  ('orders', 'order_note'),
  ('orders', 'customer_note'),
  ('orders', 'items'),
  ('orders', 'total'),
  ('orders', 'date'),
  ('orders', 'created_by_user_id'),
  ('orders', 'bigcommerce_order_id'),
  ('orders', 'google_sheets_logged'),
  ('permissions', 'id'),
  ('permissions', 'module'),
  ('permissions', 'action'),
  ('permissions', 'description'),
  ('pos_price_override_audit', 'id'),
  ('pos_price_override_audit', 'user_id'),
  ('pos_price_override_audit', 'customer_id'),
  ('pos_price_override_audit', 'customer_name'),
  ('pos_price_override_audit', 'order_id'),
  ('pos_price_override_audit', 'bigcommerce_order_id'),
  ('pos_price_override_audit', 'product_id'),
  ('pos_price_override_audit', 'product_name'),
  ('pos_price_override_audit', 'sku'),
  ('pos_price_override_audit', 'product_cost'),
  ('pos_price_override_audit', 'selling_price'),
  ('pos_price_override_audit', 'loss_amount'),
  ('pos_price_override_audit', 'created_at'),
  ('pos_store_credit_usage', 'id'),
  ('pos_store_credit_usage', 'order_id'),
  ('pos_store_credit_usage', 'bigcommerce_order_id'),
  ('pos_store_credit_usage', 'customer_id'),
  ('pos_store_credit_usage', 'customer_name'),
  ('pos_store_credit_usage', 'cashier_id'),
  ('pos_store_credit_usage', 'credit_before'),
  ('pos_store_credit_usage', 'credit_used'),
  ('pos_store_credit_usage', 'credit_remaining'),
  ('pos_store_credit_usage', 'order_total_before'),
  ('pos_store_credit_usage', 'final_order_total'),
  ('pos_store_credit_usage', 'created_at'),
  ('price_history_cache', 'id'),
  ('price_history_cache', 'customer_id'),
  ('price_history_cache', 'product_id'),
  ('price_history_cache', 'variant_id'),
  ('price_history_cache', 'price'),
  ('price_history_cache', 'order_id'),
  ('price_history_cache', 'order_date'),
  ('price_history_cache', 'created_at'),
  ('price_history_cache', 'sku'),
  ('product_link_logs', 'id'),
  ('product_link_logs', 'main_product_id'),
  ('product_link_logs', 'main_product_name'),
  ('product_link_logs', 'linked_product_id'),
  ('product_link_logs', 'linked_product_name'),
  ('product_link_logs', 'bidirectional'),
  ('product_link_logs', 'created_by_user_id'),
  ('product_link_logs', 'created_by_name'),
  ('product_link_logs', 'status'),
  ('product_link_logs', 'results'),
  ('product_link_logs', 'created_at'),
  ('products', 'id'),
  ('products', 'bigcommerce_id'),
  ('products', 'name'),
  ('products', 'sku'),
  ('products', 'price'),
  ('products', 'image'),
  ('products', 'description'),
  ('products', 'cost_price'),
  ('products', 'stock_level'),
  ('products', 'is_pinned'),
  ('products', 'is_promotion'),
  ('products', 'variants'),
  ('products', 'brand_id'),
  ('products', 'brand_name'),
  ('products', 'categories'),
  ('promo_free_sku_tracker', 'id'),
  ('promo_free_sku_tracker', 'sku'),
  ('promo_free_sku_tracker', 'product_id'),
  ('promo_free_sku_tracker', 'variant_id'),
  ('promo_free_sku_tracker', 'product_name'),
  ('promo_free_sku_tracker', 'variant_name'),
  ('promo_free_sku_tracker', 'promo_note'),
  ('promo_free_sku_tracker', 'created_by'),
  ('promo_free_sku_tracker', 'is_active'),
  ('promo_free_sku_tracker', 'created_at'),
  ('promo_free_sku_tracker', 'updated_at'),
  ('report_export_logs', 'id'),
  ('report_export_logs', 'user_id'),
  ('report_export_logs', 'user_name'),
  ('report_export_logs', 'report_name'),
  ('report_export_logs', 'view_name'),
  ('report_export_logs', 'filters'),
  ('report_export_logs', 'export_type'),
  ('report_export_logs', 'row_count'),
  ('report_export_logs', 'created_at'),
  ('role_permissions', 'id'),
  ('role_permissions', 'role_id'),
  ('role_permissions', 'permission_id'),
  ('roles', 'id'),
  ('roles', 'name'),
  ('roles', 'description'),
  ('roles', 'created_at'),
  ('settings', 'id'),
  ('settings', 'key'),
  ('settings', 'value'),
  ('shipstation_export_history', 'id'),
  ('shipstation_export_history', 'export_date'),
  ('shipstation_export_history', 'file_name'),
  ('shipstation_export_history', 'record_count'),
  ('shipstation_export_history', 'status'),
  ('shipstation_export_history', 'error_message'),
  ('shipstation_export_history', 'file_content'),
  ('shipstation_export_history', 'created_at'),
  ('store_credit_ledger', 'id'),
  ('store_credit_ledger', 'customer_id'),
  ('store_credit_ledger', 'bigcommerce_customer_id'),
  ('store_credit_ledger', 'bigcommerce_order_id'),
  ('store_credit_ledger', 'order_id'),
  ('store_credit_ledger', 'type'),
  ('store_credit_ledger', 'amount'),
  ('store_credit_ledger', 'tax'),
  ('store_credit_ledger', 'reason'),
  ('store_credit_ledger', 'products'),
  ('store_credit_ledger', 'issued_by'),
  ('store_credit_ledger', 'issued_by_name'),
  ('store_credit_ledger', 'created_at'),
  ('user_permissions', 'id'),
  ('user_permissions', 'user_id'),
  ('user_permissions', 'permission_id'),
  ('users', 'id'),
  ('users', 'username'),
  ('users', 'password'),
  ('users', 'name'),
  ('users', 'role'),
  ('users', 'is_enabled'),
  ('users', 'allow_bigcommerce_search'),
  ('users', 'role_id'),
  ('users', 'default_landing_page'),
  ('users', 'attendance_home_latitude'),
  ('users', 'attendance_home_longitude'),
  ('users', 'attendance_home_set_at')
)
SELECT e.table_name, e.column_name AS missing_column
FROM expected e
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public'
 AND c.table_name = e.table_name
 AND c.column_name = e.column_name
WHERE c.column_name IS NULL
ORDER BY e.table_name, e.column_name;

-- 3. Columns added by this upgrade, including type/nullability/default checks.
-- Missing rows indicate missing columns. Mismatch rows require manual review.
WITH expected(table_name, column_name, expected_type, expected_nullable, expected_default) AS (VALUES
  ('email_templates', 'template_type', 'text', 'NO', '''transactional'''),
  ('email_templates', 'category', 'text', 'NO', '''general'''),
  ('email_templates', 'is_active', 'boolean', 'NO', 'true'),
  ('email_templates', 'archived_at', 'timestamp without time zone', 'YES', NULL),
  ('users', 'attendance_home_latitude', 'numeric(10, 7)', 'YES', NULL),
  ('users', 'attendance_home_longitude', 'numeric(10, 7)', 'YES', NULL),
  ('users', 'attendance_home_set_at', 'timestamp without time zone', 'YES', NULL)
)
SELECT e.table_name, e.column_name, e.expected_type, c.udt_name, e.expected_nullable,
       c.is_nullable, e.expected_default, c.column_default
FROM expected e
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public' AND c.table_name = e.table_name AND c.column_name = e.column_name
LEFT JOIN pg_attribute a
  ON a.attrelid = to_regclass('public.' || e.table_name)
 AND a.attname = e.column_name
 AND a.attnum > 0
 AND NOT a.attisdropped
WHERE c.column_name IS NULL
   OR (format_type(a.atttypid, a.atttypmod) <> e.expected_type)
   OR (e.expected_nullable <> c.is_nullable)
   OR (e.expected_default IS NOT NULL AND c.column_default IS NULL)
ORDER BY e.table_name, e.column_name;

-- 4. Required indexes missing from public schema (expected: zero rows).
WITH expected(table_name, index_name) AS (VALUES
  ('attendance_audit_log', 'attendance_audit_attendance_created_idx'),
  ('attendance_exceptions', 'attendance_exceptions_status_detected_idx'),
  ('attendance_exceptions', 'attendance_exceptions_user_idx'),
  ('attendance_location_checkpoints', 'attendance_checkpoints_attendance_captured_idx'),
  ('attendance_sessions', 'attendance_sessions_user_date_idx'),
  ('attendance_sessions', 'attendance_sessions_status_idx'),
  ('bc_order_line_items', 'idx_bc_order_line_items_order_date'),
  ('bc_order_line_items', 'idx_bc_order_line_items_product'),
  ('customer_signups', 'idx_customer_signups_created_at'),
  ('customer_signups', 'idx_customer_signups_signed_up_by'),
  ('inventory_audit_tasks', 'idx_audit_tasks_sku'),
  ('inventory_audit_tasks', 'idx_audit_tasks_status'),
  ('inventory_audit_tasks', 'idx_audit_tasks_product'),
  ('marketing_audience_members', 'marketing_audience_customer_member_idx'),
  ('marketing_audience_members', 'marketing_audience_contact_member_idx'),
  ('marketing_automation_executions', 'marketing_automation_executions_automation_idx'),
  ('marketing_automation_executions', 'marketing_automation_executions_customer_idx'),
  ('marketing_automation_steps', 'marketing_automation_steps_order_idx'),
  ('marketing_campaign_events', 'marketing_campaign_events_campaign_idx'),
  ('marketing_campaign_events', 'marketing_campaign_events_recipient_idx'),
  ('marketing_campaign_recipients', 'marketing_campaign_recipients_campaign_customer_idx'),
  ('marketing_campaign_recipients', 'marketing_campaign_recipients_campaign_contact_idx'),
  ('marketing_campaign_recipients', 'marketing_campaign_recipients_status_idx'),
  ('marketing_contacts', 'marketing_contacts_type_active_idx'),
  ('marketing_suppressions', 'marketing_suppressions_active_customer_idx'),
  ('marketing_suppressions', 'marketing_suppressions_active_email_idx')
)
SELECT e.table_name, e.index_name AS missing_index
FROM expected e
LEFT JOIN pg_class i ON i.relname = e.index_name AND i.relnamespace = 'public'::regnamespace
LEFT JOIN pg_index ix ON ix.indexrelid = i.oid
WHERE i.oid IS NULL
ORDER BY e.table_name, e.index_name;

-- 5. Required foreign-key constraints missing from public schema (expected: zero rows).
WITH expected(table_name, constraint_name) AS (VALUES
  ('attendance_audit_log', 'attendance_audit_log_attendance_id_attendance_sessions_id_fk'),
  ('attendance_audit_log', 'attendance_audit_log_actor_user_id_users_id_fk'),
  ('attendance_exceptions', 'attendance_exceptions_attendance_id_attendance_sessions_id_fk'),
  ('attendance_exceptions', 'attendance_exceptions_user_id_users_id_fk'),
  ('attendance_exceptions', 'attendance_exceptions_reviewed_by_users_id_fk'),
  ('attendance_location_checkpoints', 'attendance_location_checkpoints_attendance_id_attendance_sessions_id_fk'),
  ('attendance_sessions', 'attendance_sessions_user_id_users_id_fk'),
  ('attendance_sessions', 'attendance_sessions_approved_by_users_id_fk'),
  ('crm_audit_log', 'crm_audit_log_user_id_users_id_fk'),
  ('crm_audit_log', 'crm_audit_log_customer_id_customers_mirror_id_fk'),
  ('crm_customer_notes', 'crm_customer_notes_customer_id_customers_mirror_id_fk'),
  ('crm_customer_notes', 'crm_customer_notes_created_by_users_id_fk'),
  ('crm_customer_notes', 'crm_customer_notes_assigned_to_user_id_users_id_fk'),
  ('customer_sales_rep', 'customer_sales_rep_customer_id_customers_mirror_id_fk'),
  ('customer_sales_rep', 'customer_sales_rep_assigned_user_id_users_id_fk'),
  ('customer_signup_attempts', 'customer_signup_attempts_created_by_user_id_users_id_fk'),
  ('customer_signups', 'customer_signups_signed_up_by_user_id_users_id_fk'),
  ('customer_signups', 'customer_signups_primary_rep_id_users_id_fk'),
  ('email_templates', 'email_templates_updated_by_users_id_fk'),
  ('inventory_audit_tasks', 'inventory_audit_tasks_created_by_users_id_fk'),
  ('inventory_audit_tasks', 'inventory_audit_tasks_completed_by_users_id_fk'),
  ('inventory_push_logs', 'inventory_push_logs_user_id_users_id_fk'),
  ('marketing_audience_members', 'marketing_audience_members_audience_id_marketing_audiences_id_fk'),
  ('marketing_audience_members', 'marketing_audience_members_customer_id_customers_mirror_id_fk'),
  ('marketing_audience_members', 'marketing_audience_members_marketing_contact_id_marketing_contacts_id_fk'),
  ('marketing_audiences', 'marketing_audiences_created_by_users_id_fk'),
  ('marketing_automation_executions', 'marketing_automation_executions_automation_id_marketing_automations_id_fk'),
  ('marketing_automation_executions', 'marketing_automation_executions_customer_id_customers_mirror_id_fk'),
  ('marketing_automation_steps', 'marketing_automation_steps_automation_id_marketing_automations_id_fk'),
  ('marketing_automations', 'marketing_automations_created_by_users_id_fk'),
  ('marketing_campaign_activity', 'marketing_campaign_activity_campaign_id_marketing_campaigns_id_fk'),
  ('marketing_campaign_activity', 'marketing_campaign_activity_user_id_users_id_fk'),
  ('marketing_campaign_events', 'marketing_campaign_events_campaign_id_marketing_campaigns_id_fk'),
  ('marketing_campaign_events', 'marketing_campaign_events_recipient_id_marketing_campaign_recipients_id_fk'),
  ('marketing_campaign_recipients', 'marketing_campaign_recipients_campaign_id_marketing_campaigns_id_fk'),
  ('marketing_campaign_recipients', 'marketing_campaign_recipients_customer_id_customers_mirror_id_fk'),
  ('marketing_campaign_recipients', 'marketing_campaign_recipients_marketing_contact_id_marketing_contacts_id_fk'),
  ('marketing_campaigns', 'marketing_campaigns_template_id_email_templates_id_fk'),
  ('marketing_campaigns', 'marketing_campaigns_created_by_users_id_fk'),
  ('marketing_contacts', 'marketing_contacts_created_by_users_id_fk'),
  ('marketing_customer_preferences', 'marketing_customer_preferences_customer_id_customers_mirror_id_fk'),
  ('marketing_customer_preferences', 'marketing_customer_preferences_updated_by_users_id_fk'),
  ('marketing_suppressions', 'marketing_suppressions_customer_id_customers_mirror_id_fk'),
  ('marketing_suppressions', 'marketing_suppressions_created_by_users_id_fk'),
  ('marketing_suppressions', 'marketing_suppressions_revoked_by_users_id_fk'),
  ('notifications', 'notifications_user_id_users_id_fk'),
  ('notifications', 'notifications_customer_id_customers_mirror_id_fk'),
  ('orders', 'orders_created_by_user_id_users_id_fk'),
  ('pos_price_override_audit', 'pos_price_override_audit_user_id_users_id_fk'),
  ('pos_store_credit_usage', 'pos_store_credit_usage_cashier_id_users_id_fk'),
  ('product_link_logs', 'product_link_logs_created_by_user_id_users_id_fk'),
  ('role_permissions', 'role_permissions_role_id_roles_id_fk'),
  ('role_permissions', 'role_permissions_permission_id_permissions_id_fk'),
  ('store_credit_ledger', 'store_credit_ledger_customer_id_customers_mirror_id_fk'),
  ('store_credit_ledger', 'store_credit_ledger_issued_by_users_id_fk'),
  ('user_permissions', 'user_permissions_permission_id_permissions_id_fk')
)
SELECT e.table_name, e.constraint_name AS missing_foreign_key
FROM expected e
LEFT JOIN pg_constraint c
  ON c.conname = e.constraint_name
 AND c.conrelid = to_regclass('public.' || e.table_name)
 AND c.contype = 'f'
WHERE c.oid IS NULL
ORDER BY e.table_name, e.constraint_name;

-- 6. Required unique constraints missing from public schema (expected: zero rows).
WITH expected(table_name, constraint_name) AS (VALUES
  ('customer_orders_mirror', 'customer_orders_mirror_bigcommerce_order_id_unique'),
  ('customer_signups', 'customer_signups_bigcommerce_customer_id_unique'),
  ('customers_mirror', 'customers_mirror_bigcommerce_customer_id_unique'),
  ('email_templates', 'email_templates_key_unique'),
  ('marketing_automation_executions', 'marketing_automation_executions_dedupe_key_unique'),
  ('marketing_contacts', 'marketing_contacts_email_unique'),
  ('marketing_customer_preferences', 'marketing_customer_preferences_customer_id_unique'),
  ('products', 'products_bigcommerce_id_unique'),
  ('promo_free_sku_tracker', 'promo_free_sku_tracker_sku_unique'),
  ('roles', 'roles_name_unique'),
  ('settings', 'settings_key_unique'),
  ('users', 'users_username_unique')
)
SELECT e.table_name, e.constraint_name AS missing_unique_constraint
FROM expected e
LEFT JOIN pg_constraint c
  ON c.conname = e.constraint_name
 AND c.conrelid = to_regclass('public.' || e.table_name)
 AND c.contype = 'u'
WHERE c.oid IS NULL
ORDER BY e.table_name, e.constraint_name;

-- 7. Required identity columns missing identity generation (expected: zero rows).
WITH expected(table_name, column_name) AS (VALUES
  ('attendance_audit_log', 'id'),
  ('attendance_exceptions', 'id'),
  ('attendance_location_checkpoints', 'id'),
  ('attendance_sessions', 'id'),
  ('bc_order_line_items', 'id'),
  ('crm_audit_log', 'id'),
  ('crm_customer_notes', 'id'),
  ('customer_orders_mirror', 'id'),
  ('customer_sales_rep', 'id'),
  ('customer_signups', 'id'),
  ('customers_mirror', 'id'),
  ('email_templates', 'id'),
  ('inventory_audit_tasks', 'id'),
  ('inventory_push_logs', 'id'),
  ('marketing_audience_members', 'id'),
  ('marketing_audiences', 'id'),
  ('marketing_automation_executions', 'id'),
  ('marketing_automation_steps', 'id'),
  ('marketing_automations', 'id'),
  ('marketing_campaign_activity', 'id'),
  ('marketing_campaign_events', 'id'),
  ('marketing_campaign_recipients', 'id'),
  ('marketing_campaigns', 'id'),
  ('marketing_contacts', 'id'),
  ('marketing_customer_preferences', 'id'),
  ('marketing_suppressions', 'id'),
  ('notifications', 'id'),
  ('orders', 'id'),
  ('permissions', 'id'),
  ('pos_price_override_audit', 'id'),
  ('pos_store_credit_usage', 'id'),
  ('price_history_cache', 'id'),
  ('product_link_logs', 'id'),
  ('products', 'id'),
  ('promo_free_sku_tracker', 'id'),
  ('report_export_logs', 'id'),
  ('role_permissions', 'id'),
  ('roles', 'id'),
  ('settings', 'id'),
  ('shipstation_export_history', 'id'),
  ('store_credit_ledger', 'id'),
  ('user_permissions', 'id'),
  ('users', 'id')
)
SELECT e.table_name, e.column_name, c.identity_generation
FROM expected e
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public' AND c.table_name = e.table_name AND c.column_name = e.column_name
WHERE c.column_name IS NULL OR c.identity_generation <> 'ALWAYS'
ORDER BY e.table_name, e.column_name;

-- 8. Added-column presence summary (expected: one row per added column).
WITH expected(table_name, column_name) AS (VALUES
  ('email_templates', 'template_type'),
  ('email_templates', 'category'),
  ('email_templates', 'is_active'),
  ('email_templates', 'archived_at'),
  ('users', 'attendance_home_latitude'),
  ('users', 'attendance_home_longitude'),
  ('users', 'attendance_home_set_at')
)
SELECT e.table_name, e.column_name, (c.column_name IS NOT NULL) AS present
FROM expected e
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public' AND c.table_name = e.table_name AND c.column_name = e.column_name
ORDER BY e.table_name, e.column_name;

-- 9. Backup/legacy tables are intentionally not inspected or modified by the upgrade.
-- This query only reports their current existence and is read-only.
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
    'orders_backup', 'products_backup', 'settings_backup', 'users_backup',
    'price_history_cache_backup', 'price_history_cache_backup2',
    'price_history_cache_05112026_live'
  )
ORDER BY table_name;